ALTER TABLE customer_products 
ADD COLUMN IF NOT EXISTS "order" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS plafon_min BIGINT NULL,
ADD COLUMN IF NOT EXISTS tenor_min VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS plafon_max VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS tenor_max VARCHAR(100) NULL;