ALTER TABLE customer_products
DROP COLUMN IF EXISTS tenor_min,
DROP COLUMN IF EXISTS plafon_max,
DROP COLUMN IF EXISTS tenor_max;

ALTER TABLE customer_products 
ADD COLUMN IF NOT EXISTS tenor_min VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS plafon_max VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS tenor_max VARCHAR(100) NULL;