ALTER TABLE customer_products
DROP COLUMN IF EXISTS tenor_min,
DROP COLUMN IF EXISTS plafon_max,
DROP COLUMN IF EXISTS tenor_max;

ALTER TABLE customer_products
ADD COLUMN IF NOT EXISTS tenor_min BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS plafon_max BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS tenor_max BIGINT DEFAULT 0;