name: Go Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: self-hosted  # Gunakan self-hosted runner Linux kamu
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build binary
      run: |
        go build -o my-app ./cmd/api/main.go
        ls -lh
        file my-app
        chmod +x my-app

    - name: Run tests
      run: go test -v ./...

    - name: Run server (background)
      run: |
        pkill -f ./my-app || true
        nohup ./my-app > server.log 2>&1 &
        sleep 3  # beri waktu untuk booting server

    - name: Cek apakah server berjalan
      run: |
        ps aux | grep my-app
        curl --fail http://localhost:8080 || echo "Server tidak merespons di port 8080"

    - name: Tampilkan log server
      run: |
        echo "===== Isi server.log ====="
        tail -n 20 server.log || echo "Log belum tersedia"
