name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted  # Semua langkah dijalankan di self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -o myapp ./cmd

      - name: Run tests
        run: go test -v ./...

      - name: Deploy binary locally (runner = server target)
        run: |
          mkdir -p /home/hendra/app
          cp ./myapp /home/hendra/app/

      - name: Restart application using PM2
        run: |
          pm2 restart myapp || pm2 start /home/hendra/app/myapp --name myapp
